require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '14.0'
install! 'cocoapods', :deterministic_uuids => false

target 'Quests' do
  config = use_native_modules!

  # Flags change depending on the env values.
  flags = get_default_flags()

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => flags[:hermes_enabled],
    :fabric_enabled => flags[:fabric_enabled],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )


  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable the next line.
  use_flipper!()

  post_install do |installer|
    react_native_post_install(installer)
    __apply_Xcode_12_5_M1_post_install_workaround(installer)
  end
end


# require File.join(File.dirname(`node --print "require.resolve('expo/package.json')"`), "scripts/autolinking")
# require File.join(File.dirname(`node --print "require.resolve('react-native/package.json')"`), "scripts/react_native_pods")
# require File.join(File.dirname(`node --print "require.resolve('@react-native-community/cli-platform-ios/package.json')"`), "native_modules")

# platform :ios, '14.0'

# require 'json'
# podfile_properties = JSON.parse(File.read('./Podfile.properties.json')) rescue {}

# target 'Quests' do
#   use_expo_modules!
#   config = use_native_modules!

#   use_react_native!(
#     :path => config[:reactNativePath],
#     :hermes_enabled => podfile_properties['expo.jsEngine'] == 'hermes'
#   )

#   # Uncomment to opt-in to using Flipper
  
#   if !ENV['CI']
#     use_flipper!('Flipper' => '0.75.1', 'Flipper-Folly' => '2.5.3', 'Flipper-RSocket' => '1.3.1')
#   end

  
#   pod 'RNGestureHandler', :path => '../node_modules/react-native-gesture-handler'

#   post_install do |installer|
#     react_native_post_install(installer)

#     # Workaround `Cycle inside FBReactNativeSpec` error for react-native 0.64
#     # Reference: https://github.com/software-mansion/react-native-screens/issues/842#issuecomment-812543933
#     installer.pods_project.targets.each do |target|
#       if (target.name&.eql?('FBReactNativeSpec'))
#         target.build_phases.each do |build_phase|
#           if (build_phase.respond_to?(:name) && build_phase.name.eql?('[CP-User] Generate Specs'))
#             target.build_phases.move(build_phase, 0)
#           end
#         end
#       end
#     end
#   end

#   post_integrate do |installer|
#     begin
#       expo_patch_react_imports!(installer)
#     rescue => e
#       Pod::UI.warn e
#     end
#   end

# end
